#!/usr/bin/env python3
# Render wild/sweep-results.tsv into a human catalog (wild/CATALOG.md).
import sys, csv

EMOJI = {
    "ok": "✅", "drift": "🕒", "no-host-cc": "🔧", "includes-dot": "📦",
    "dep-shape": "📦", "timeout": "⏱️", "fail": "❌", "-": "·",
}
LEGEND = (
    "✅ builds · 🕒 Bazel-version drift (cc_*/sh_test autoload removed in Bazel 9) · "
    "🔧 needs a host C/C++ toolchain · 📦 build/consumption-shape issue (e.g. `includes=[\".\"]`, "
    "built-as-dep) · ⏱️ timed out · ❌ other failure · · n/a"
)

def cell(v): return f"{EMOJI.get(v, '❔')} {v}"

rows = list(csv.DictReader(open(sys.argv[1]), delimiter="\t"))
rows.sort(key=lambda r: (r["as_is"] != "ok", r["right_bazel"] != "ok", r["key"]))

n = len(rows)
ok_asis = sum(r["as_is"] == "ok" for r in rows)
ok_right = sum(r["right_bazel"] == "ok" for r in rows)
herm = sum(r["hermetic"] == "ok" for r in rows)

print("# wild catalog — museum projects built as they are\n")
print("Generated by [`sweep.sh`](sweep.sh) from [`sweep-results.tsv`](sweep-results.tsv). "
      "Each project's *curated build target* (from its museum BUILD) run in the wild "
      "containers — upstream MODULE/BUILD, no overlays, no injected toolchain.\n")
print("Columns:")
print("- **as-is** — baseline image (a normal CI machine), whatever Bazel bazelisk picks.")
print("- **+right-bazel** — baseline image, pinned to the project's known-good Bazel "
      "(isolates Bazel-version drift from everything else).")
print("- **hermetic** — *strict* image (nothing but bazelisk), known-good Bazel. ✅ here "
      "means the project builds with no host toolchain at all — hermetic in nature. Only "
      "attempted when **+right-bazel** builds.\n")
print(f"**{ok_asis}/{n}** build as-is · **{ok_right}/{n}** with the right Bazel · "
      f"**{herm}/{n}** are hermetic in nature.\n")
print(f"_{LEGEND}_\n")
print("| project | declared Bazel | as-is | +right-bazel | hermetic | note |")
print("|---------|:--------------:|:-----:|:------------:|:--------:|------|")
for r in rows:
    note = r.get("note", "").replace("|", "\\|")
    print(f"| {r['key']} | {r['version']} | {cell(r['as_is'])} | {cell(r['right_bazel'])} "
          f"| {cell(r['hermetic'])} | {note} |")
