"""Render the full ranked candidate universe to a markdown roadmap.

Every PROJECT-category, non-archived entry in data/projects.json, ordered by
candidate score (the same recognition x alive x buildable score //pipeline:rank
uses), with the ones already in the museum flagged. This is the "where are we
headed" view: the whole field in priority order, not just the next 30.

    python3 pipeline/_ranked_doc.py > docs/roadmap.md

Built-status is derived from runner/_readme_table.META so it stays in sync with
the actual museum (builds/<dir>) instead of a hand-maintained list.
"""

import json
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)
sys.path.insert(0, os.path.join(_ROOT, "runner"))

from pipeline import model  # noqa: E402
from pipeline.rank import _as_project, _slug  # noqa: E402
from _readme_table import META  # noqa: E402

# Repo slugs already in the museum (builds/<dir>), from the README metadata.
BUILT = {repo.rstrip("/").rsplit("/", 1)[-1].lower()
         for _, repo, _ in META.values() if repo}


def _buildable(p):
    if p.in_bcr and p.first_party_bazel is True:
        return "BCR · 1st-party"
    if p.in_bcr and p.first_party_bazel is False:
        return "BCR · ported"
    if p.in_bcr:
        return "BCR"
    if p.first_party_bazel is True:
        return "1st-party"
    if p.first_party_bazel is False:
        return "ported"
    return "?"


def main():
    path = os.path.join(_ROOT, "data", "projects.json")
    doc = json.load(open(path, encoding="utf-8"))
    reference = doc.get("reference_pushed_at") or max(
        (d.get("pushed_at", "") for d in doc["projects"]), default="")

    cands = []
    for d in doc["projects"]:
        if d.get("category") != model.CATEGORY_PROJECT or d.get("archived"):
            continue
        p = _as_project(d)
        cands.append((model.candidate_score(p, reference), p))
    cands.sort(key=lambda sp: (-sp[0], -sp[1].stars, sp[1].key))

    n_built = sum(1 for _, p in cands if _slug(p.repo_url) in BUILT)

    print("# Museum roadmap — ranked candidate projects")
    print()
    print("_Generated by `python3 pipeline/_ranked_doc.py` from "
          "`data/projects.json` (snapshot reference `%s`)._" % (reference or "n/a"))
    print()
    print("All %d non-archived PROJECT-category candidates, ranked by candidate "
          "score (`log10(stars) x freshness x buildable`, where BCR=+1 and "
          "first-party Bazel=+0.5). ✅ marks the %d already in the museum."
          % (len(cands), n_built))
    print()
    print("| # | In museum | Score | Stars | Buildability | Language | Project |")
    print("|--:|:---------:|------:|------:|:-------------|:---------|:--------|")
    for i, (score, p) in enumerate(cands, 1):
        built = "✅" if _slug(p.repo_url) in BUILT else ""
        print("| %d | %s | %.2f | %s | %s | %s | [%s](%s) |"
              % (i, built, score, f"{p.stars:,}", _buildable(p),
                 p.language or "?", p.key, p.repo_url))


if __name__ == "__main__":
    main()
